
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
  prometheus:
    image:
      prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image:
      grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana      


volumes:
  grafana-storage:
    
